fix: import multiple segmentations from coco format json
HumanSignal/label-studio-sdk pull request #251
Opened 2024-06-19 01:57 UTC by Ljung323

# Issue
https://github.com/HumanSignal/label-studio-sdk/issues/246

# Changes
- d5287ad4e7a887589345aeb04ab89ad508e6abe2 pass all segmentation items to `create_segmentation` function

# Test
## original image with segmentation
<img src="https://github.com/HumanSignal/label-studio-sdk/assets/82586164/eaaf4f7b-2857-44e7-bbf8-1758ef5d6108" height=50%>

## before change: only 1 section is imported
<img src="https://github.com/HumanSignal/label-studio-sdk/assets/82586164/c0637087-56ca-4965-8d64-b6d083dba312" width=50%>

## after change: all 5 sections are imported
<img src="https://github.com/HumanSignal/label-studio-sdk/assets/82586164/55585aa5-2cfc-4b1d-a86f-c0976b1a0100" width=50%>

2024-06-19 02:03 UTC, Ljung323 commented on src/label_studio_sdk/converter/imports/coco.py
> +        help="input COCO json file",
fixed to be consistent with: (not discussed in the original issue though)
https://github.com/HumanSignal/label-studio-sdk/blob/a67c59c724aaed8e0abdd368e4dea07306c78398/src/label_studio_sdk/converter/imports/coco.py#L120

2024-06-19 02:06 UTC, Ljung323 commented on src/label_studio_sdk/converter/imports/coco.py
> +    category_id, segmentation, categories, from_name, image_height, image_width, to_name
due to the change from this PR, there's no need to pass the whole annotation.
so updated to pass `annotation["category_id"]` and `segmentation`

2024-06-19 02:06 UTC, Ljung323 commented on src/label_studio_sdk/converter/imports/coco.py
> +            for single_segmentation in annotation["segmentation"]:
to avoid conflicts with other `segmentation` variables, named it as `single_segmentation`

2024-08-05 21:55 UTC, makseq commented
/git update master

2024-08-05 22:12 UTC, makseq commented
Could you please update your branch and merge the lastest master branch from the main repo?

2024-08-05 22:13 UTC, makseq commented
Is it possible to add test for coco import? Something like this: https://github.com/Ljung323/label-studio-sdk/blob/master/tests/custom/converter/test_import_yolo.py

You can merely run the converter on a real simple COCO json, get its output and use it for test assertion. It would be wonderful to have it.

2024-08-05 22:25 UTC, makseq requested changes
1. Please update to the latest master branch
2. Could you add a test?

2024-08-06 07:58 UTC, Ljung323 commented
@makseq 
Thank you very much for the review.

I updated the code:

> 1. Please update to the latest master branch

92f6927

> 2. Could you add a test?

a3c8ba7 da9abcb

2024-08-07 09:26 UTC, makseq approved these changes

2024-08-16 20:35 UTC, merged